version: '3'

services:
  nginx_proxy:
    image: nginx:1.21.5-alpine
    container_name: nginx_proxy    
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      
  app:
    image: ${DOCKER_HUB_USER}/frontend:frontend-latest
    ports:
      - '3000:3000'
    env_file:
      - ./.env

  


