server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  redis:
    #  host: 127.0.0.1
     host: i10a709.p.ssafy.io
     port: 6379
     password: ssafy709
  datasource:
    #  url: jdbc:mariadb://localhost:3306/security
     url: jdbc:mariadb://i10a709.p.ssafy.io:3306/security
     username: root
     password: ssafy709
     driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    generate-ddl: true
#    show-sql: true
    hibernate:
        ddl-auto: update
      


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  logging:
  level:
  org.hibernate.SQL: debug
#      org.hibernate.type: trace
  profiles:
    active: local
    include: jwt

file:
  upload:
    directory: /tmp/coala/data/
    

