server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



  data:
    mongodb:
      host: localhost
      port: 27017
      database: tutorial
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update

      naming:
        physical-strategy=org:
          hibernate:
            boot:
              model:
                naming:
                  PhysicalNamingStrategyStandardImpl:properties:
      hibernate:
        format_sql: true
        show_sql: true

  logging:
  level:
  org.hibernate.SQL: debug
#      org.hibernate.type: trace
  profiles:
    active: local
    include: oauth, jwt


